// examples/tanstack-start-app/src/routes/index.tsx
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { useRef, useEffect } from 'react'
import { setDirection, setupPage } from '@capgo/capacitor-transitions/react'

function HomePage() {
  const navigate = useNavigate()
  const pageRef = useRef<HTMLElement>(null)

  useEffect(() => {
    if (pageRef.current) {
      return setupPage(pageRef.current, {
        onDidEnter: () => console.log('Home entered'),
        onDidLeave: () => console.log('Home left'),
      })
    }
  }, [])

  const goToDetails = (id: number) => {
    setDirection('forward')
    navigate({ to: '/details/$id', params: { id: String(id) } })
  }

  return (
    <cap-page ref={pageRef}>
      <cap-header slot="header">
        <div className="toolbar">
          <h1>Home</h1>
        </div>
      </cap-header>
      <cap-content slot="content">
        <div className="page-content">
          <h2>TanStack Start + Cap Transitions</h2>
          <p>This example shows iOS-style page transitions with TanStack Start.</p>

          <div className="list">
            {[1, 2, 3, 4, 5].map((id) => (
              <button key={id} className="list-item" onClick={() => goToDetails(id)}>
                <span>Item {id}</span>
                <span className="chevron">›</span>
              </button>
            ))}
          </div>
        </div>
      </cap-content>
      <cap-footer slot="footer">
        <div className="tab-bar">
          <button className="tab active">Home</button>
          <button className="tab">Search</button>
          <button className="tab">Profile</button>
        </div>
      </cap-footer>
    </cap-page>
  )
}

export const Route = createFileRoute('/')({
  component: HomePage,
})

// examples/sveltekit-app/src/routes/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { page, setDirection } from '@capgo/capacitor-transitions/svelte'

  const goToDetails = (id: number) => {
    setDirection('forward')
    goto(`/details/${id}`)
  }
</script>

<cap-page use:page={{
  onDidEnter: () => console.log('Home entered'),
  onDidLeave: () => console.log('Home left'),
}}>
  <cap-header slot="header">
    <div class="toolbar">
      <h1>Home</h1>
    </div>
  </cap-header>
  <cap-content slot="content">
    <div class="page-content">
      <h2>SvelteKit + Cap Transitions</h2>
      <p>This example shows iOS-style page transitions with SvelteKit.</p>

      <div class="list">
        {#each [1, 2, 3, 4, 5] as id}
          <button class="list-item" on:click={() => goToDetails(id)}>
            <span>Item {id}</span>
            <span class="chevron">›</span>
          </button>
        {/each}
      </div>
    </div>
  </cap-content>
  <cap-footer slot="footer">
    <div class="tab-bar">
      <button class="tab active">Home</button>
      <button class="tab">Search</button>
      <button class="tab">Profile</button>
    </div>
  </cap-footer>
</cap-page>
