// examples/sveltekit-app/src/routes/details/[id]/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { page as pageStore } from '$app/stores'
  import { page, setDirection } from '@capgo/capacitor-transitions/svelte'

  $: id = $pageStore.params.id

  const goBack = () => {
    setDirection('back')
    goto('/')
  }

  const goDeeper = () => {
    setDirection('forward')
    goto(`/nested/${id}`)
  }
</script>

<cap-page use:page={{
  onDidEnter: () => console.log(`Details ${id} entered`),
  onDidLeave: () => console.log(`Details ${id} left`),
}}>
  <cap-header slot="header">
    <div class="toolbar">
      <button class="back-button" on:click={goBack}>‹ Back</button>
      <h1>Details {id}</h1>
    </div>
  </cap-header>
  <cap-content slot="content">
    <div class="page-content">
      <h2>Detail View</h2>
      <p>This is the details page for item {id}.</p>
      <p>SvelteKit works seamlessly with Cap Transitions.</p>

      <button class="primary-button" on:click={goDeeper}>Go Deeper</button>

      <div class="scroll-demo">
        <h3>Scroll Content</h3>
        {#each Array.from({ length: 20 }) as _, i}
          <p>Scroll item {i + 1}</p>
        {/each}
      </div>
    </div>
  </cap-content>
</cap-page>

// examples/nextjs-app/src/app/details/[id]/page.tsx
'use client'

import { useRef, useEffect } from 'react'
import { useRouter, useParams } from 'next/navigation'
import { setDirection, setupPage } from '@capgo/capacitor-transitions/react'

export default function DetailsPage() {
  const router = useRouter()
  const params = useParams()
  const id = params.id as string
  const pageRef = useRef<HTMLElement>(null)

  useEffect(() => {
    if (pageRef.current) {
      return setupPage(pageRef.current, {
        onDidEnter: () => console.log(`Details ${id} entered`),
        onDidLeave: () => console.log(`Details ${id} left`),
      })
    }
  }, [id])

  const goBack = () => {
    setDirection('back')
    router.push('/')
  }

  const goDeeper = () => {
    setDirection('forward')
    router.push(`/nested/${id}`)
  }

  return (
    <cap-page ref={pageRef}>
      <cap-header slot="header">
        <div className="toolbar">
          <button className="back-button" onClick={goBack}>
            ‹ Back
          </button>
          <h1>Details {id}</h1>
        </div>
      </cap-header>
      <cap-content slot="content">
        <div className="page-content">
          <h2>Detail View</h2>
          <p>This is the details page for item {id}.</p>
          <p>Next.js App Router works seamlessly with Cap Transitions.</p>

          <button className="primary-button" onClick={goDeeper}>
            Go Deeper
          </button>

          <div className="scroll-demo">
            <h3>Scroll Content</h3>
            {Array.from({ length: 20 }).map((_, i) => (
              <p key={i}>Scroll item {i + 1}</p>
            ))}
          </div>
        </div>
      </cap-content>
    </cap-page>
  )
}
